### ISSUE TITLE
Issue when pasting from Illustrator

### ISSUE THREAD

**Issue by PierBover** [jakearchibald/svgomg#145] opened 2018-10-29 00:16 UTC
When copying and pasting from Illustrator into SVGOMG I get this error:

> Load failed: Error in parsing SVG: Text data outside of root node. Line: 13 Column: 1 Char:

The weird thing is, if I paste the markup into a text editor, and then copy and paste exactly the same thing, it works fine.

Here's the markup for that error:

```html
<!-- Generator: Adobe Illustrator 22.1.0, SVG Export Plug-In  -->
<svg version="1.1"
	 xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:a="http://ns.adobe.com/AdobeSVGViewerExtensions/3.0/"
	 x="0px" y="0px" width="65px" height="65px" viewBox="0 0 65 65" style="enable-background:new 0 0 65 65;" xml:space="preserve">
<style type="text/css">
	.st0{fill:#FFFFFF;}
	.st1{fill:none;}
</style>
<defs>
</defs>
<path class="st0" d="M38,9.5H13.8v46h37.4V22.7L38,9.5z M45.4,49.8H19.6V15.2h16.1l1.2,1.2v7.4h7.4l1.2,1.2V49.8z"/>
<rect class="st1" width="65" height="65"/>
</svg>
```

Using [this tool](https://www.soscisurvey.de/tools/view-chars.php) there appears to be a `00` character in there messing things up:

![image](https://user-images.githubusercontent.com/226483/47624044-df171d00-dae5-11e8-972b-7ab2c08dbc38.png)

Would you accept a PR to trim hidden characters when pasting?

**Comment by XhmikosR** [comment] 2021-09-12 14:56
@jakearchibald this seems a duplicate of #68

**Comment by jakearchibald** [comment] 2021-09-14 08:42
Agreed

**Closed by jakearchibald** 2021-09-14 08:42 UTC
