### ISSUE TITLE
[Feature Request] Copy to Clipboard

### ISSUE THREAD

**Issue by vinkla** [jakearchibald/svgomg#38] opened 2015-11-19 14:15 UTC
The ability to copy the code to the clipboard. Right now it is quite hard to copy paste since the sidebar content is copyable. What do you think? Something you would consider adding?

**Comment by feca1997** [comment] 2016-02-25 23:07
Maybe use [clipboard.js](https://clipboardjs.com)?

**Comment by jakearchibald** [comment] 2016-03-19 11:54
Dupe of #22

**Closed by jakearchibald** 2016-03-19 11:54 UTC
