### ISSUE TITLE
Export chosen settings as a command line to run command version of svgo

### ISSUE THREAD

**Issue by theghostbel** [jakearchibald/svgomg#50] opened 2016-06-28 15:39 UTC

**Comment by Haroenv** [comment] 2017-03-17 10:03
Would love to see this happen!

**Comment by ericcornelissen** [comment] 2018-10-22 19:47
Just for administration, isn't this a duplicate of #11?

Certainly would be interested in this as well tho 😄

**Comment by harold** [comment] 2021-03-17 17:05
+1

**Comment by XhmikosR** [comment] 2022-10-27 16:01
Duplicate of #11

**Closed by XhmikosR** 2022-10-27 16:01 UTC
